### ISSUE TITLE
Saving SQL passwords in Excel Power Pivot Connections

### ISSUE THREAD

**Issue by xaratsarhs** [kevinoid/kevinlocke.name#2]
Hello Kevin and thank you for this useful tutorial.
I have a problem involving saved passwords and I wonder if you could help me.

I want to change the password that is already saved at the connection string (following your steps) and now that they are saved I can not change them. The problem is that even if I change the password at the connection properties (refresh is working perfectly) when I go to manage the table (for example to change the year that I want to retrieve) from the table properties I get an error msg during the preview that the connection string is closed.

"ExecuteReader requires an open and available Connection. The connection's current state is closed"

Do you know how to reset the password or unsaved it some how?

Thank you in advance 
Harris from Greece
xaratsarhs at gmail.com

**Comment by kevinoid** [comment]
Hello Harris,

I haven't run into that particular error before, but I have encountered difficulty changing the saved password.  In my experience it is necessary to disable password saving for the connection, then re-enable it.  Otherwise the old password isn't changed everywhere and errors occur.  I would suggest trying the following:

1.  Edit the connection in Power Pivot and un-check "Save my password".
2.  Excel the connection in Excel Data Connections and un-check "Save password".
3.  Save and exit Excel to clear cached passwords.
4.  Open Excel and "Refresh All" to confirm it prompts you for the connection password and that the new password works (you may still get an error if the query is wrong, but that's ok for now).
5.  Follow the steps in "Saving SQL passwords in Excel Power Pivot Connections" to save the new password.
6.  Edit the connection to make any changes you want.

Best of luck,
Kevin

**Comment by xaratsarhs** [comment]
No luck Kevin,
it still remembers the old password when I click to Remember it at connection string in power pivot.
Thank you for your time.
If you ever find a solution please let me know.

Best regards
Harris from Greece
xaratsarhs at gmail.com
